dist: xenial
addons:
  apt:
    update: true
language: c
compiler:
  - clang
  - gcc
install: ./autogen.sh
script:
  - ./configure --enable-warn-all
  - make dist
  - tar zxvf *.tar.gz
  - cd tinyframe-[0-9]*
  - mkdir build
  - cd build
  - ../configure --enable-warn-all
  - make
  - make test
  - cat src/test/test*.sh.log
